version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 10
    reviewers:
      - "filipowm"
    labels:
      - "dependencies"
      - "java"
    commit-message:
      prefix: "build"
      include: "scope"
    groups:
      spring:
        patterns:
          - "org.springframework*"
      test:
        patterns:
          - "*junit*"
          - "*mockito*"
          - "*assertj*"
          - "*awaitility*"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    open-pull-requests-limit: 5
    reviewers:
      - "filipowm"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"